import Head from 'next/head';
import styled from 'styled-components';
import { PostCard, Categories, PostWidget } from '../components';
import { getPosts } from '../services';

export default function Home({ posts }) {
  return (
    <Container>
      <Head>
        <title>h2h Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperPage>
        <div className="post">
          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
        </div>
        <div className="post-widget">
          <div className="post-widget__wrapper">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </WrapperPage>
    </Container>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts }
  };
}

export const Container = styled.div`
  width: 100%;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: center;
`;

export const WrapperPage = styled.div`
  display: flex;
  @media screen and (max-width: 920px) {
    flex-direction: column;
  }
  width: 100%;
  box-sizing: border-box;
  .post {
    width: 80%;
    @media screen and (max-width: 920px) {
      width: 100%;
    }
  }
  .post-widget {
    .post-widget__wrapper {
      position: sticky;
      top: 20px;
    }
  }
`;
