import Head from 'next/head';
import { useState } from 'react';
import styled from 'styled-components';
import { ArrowBack } from '../assets/images/vectors/ArrowBack';
import { PostCard, Categories, PostWidget } from '../components';
import { getPosts } from '../services';

export default function Home({ posts }) {
  const [postNum, setPostNum] = useState(3);

  const handleClick = () => {
    setPostNum((prev) => prev + 3);
  };
  return (
    <Container>
      <Head>
        <title>h2h Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperPage>
        <div className="post">
          {posts.slice(0, postNum).map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
          {postNum >= posts.length ? (
            ''
          ) : (
            <ButtonMore onClick={handleClick}>
              Załaduj więcej <ArrowBack />
            </ButtonMore>
          )}
        </div>
        <div className="post-widget">
          <div className="post-widget__wrapper">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </WrapperPage>
    </Container>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts }
  };
}

export const ButtonMore = styled.button`
  color: ${({ theme }) => theme.primaryColor};
  font-size: ${({ theme }) => theme.fontSize.smallText};
  font-weight: 200;
  letter-spacing: 1px;
  background-color: transparent;
  cursor: pointer;
  border: 0;
  text-transform: uppercase;
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: 20px;
  svg {
    animation: bounce 2s infinite;
    width: 25px;
    height: 25px;
    margin-top: 7px;
    path {
      stroke: ${({ theme }) => theme.primaryColor};
    }
  }
  @keyframes bounce {
    0%,
    20%,
    50%,
    80%,
    100% {
      transform: translateY(0);
    }
    40% {
      transform: translateY(-10px);
    }
    60% {
      transform: translateY(-5px);
    }
  }
`;

export const Container = styled.div`
  width: 100%;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: center;
`;

export const WrapperPage = styled.div`
  display: flex;
  @media screen and (max-width: 920px) {
    flex-direction: column;
  }
  width: 100%;
  box-sizing: border-box;
  .post {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 80%;
    @media screen and (max-width: 920px) {
      width: 100%;
    }
  }
  .post-widget {
    .post-widget__wrapper {
      position: sticky;
      top: 112px;
    }
  }
`;
