import Head from 'next/head';
import styled from 'styled-components';
import { PostCard, Categories, PostWidget } from '../components';
import { getPost } from '../services';

export default function Home({ posts }) {
  return (
    <Container>
      <Head>
        <title>h2h Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WrapperPage>
        <div className="post">
          {posts.map((post) => (
            <PostCard key={post.title} post={post.node} />
          ))}
        </div>
        <div className="post-widget">
          <div className="post-widget_wrapper">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </WrapperPage>
    </Container>
  );
}

export async function getStaticProps() {
  const posts = (await getPost()) || [];
  return {
    props: { posts }
  };
}

export const Container = styled.div`
  max-width: 1300px;
  margin: 0 auto;
`;

export const WrapperPage = styled.div`
  margin: 0 auto;
  display: flex;
  .post {
    width: 80%;
  }
`;
